export const mockedUsers = [
  {
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@example.com',
    password: 'examplePassword123!@#',
    domicile: 'New York',
    gender: 'male',
    dateOfBirth: '1999-12-21',
  },
  {
    firstName: 'Jane',
    lastName: 'Doe',
    email: 'janedoe@example.com',
    password: 'examplePassword123!@#',
    domicile: 'London',
    gender: 'female',
    dateOfBirth: '2000-01-31',
  },
  {
    firstName: 'Max',
    lastName: 'Mustermann',
    email: 'maxmustermann@example.com',
    password: 'examplePassword123!@#',
    domicile: 'Berlin',
    gender: 'male',
    dateOfBirth: '1989-07-12',
  },
  {
    firstName: 'Jan',
    lastName: 'Kowalski',
    email: 'jankowalski@example.com',
    password: 'examplePassword123!@#',
    domicile: 'Warsaw',
    gender: 'male',
    dateOfBirth: '1997-10-09',
  },
  {
    firstName: 'Anna',
    lastName: 'Kowalska',
    email: 'annakowalska@example.com',
    password: 'examplePassword123!@#',
    domicile: 'Cracow',
    gender: 'female',
    dateOfBirth: '1975-09-27',
  },
  {
    firstName: 'Iwan',
    lastName: 'Pietrowicz',
    email: 'iwanpietrowicz@example.com',
    password: 'examplePassword123!@#',
    domicile: 'Moscow',
    gender: 'male',
    dateOfBirth: '1986-02-28',
  },
  {
    firstName: 'Gall',
    lastName: 'Anonim',
    email: 'gallanonim@example.com',
    password: 'examplePassword123!@#',
    domicile: 'Paris',
    gender: 'male',
    dateOfBirth: '1066-01-01',
  },
  {
    firstName: 'Pop',
    lastName: 'Smoke',
    email: 'popsmoke@example.com',
    password: 'examplePassword123!@#',
    domicile: 'New York',
    gender: 'male',
    dateOfBirth: '1999-07-20',
  },
  {
    firstName: '50',
    lastName: 'Cent',
    email: '50cent@example.com',
    password: 'examplePassword123!@#',
    domicile: 'New York',
    gender: 'male',
    dateOfBirth: '1975-07-06',
  },
  {
    firstName: 'Snoop',
    lastName: 'Dogg',
    email: 'snoopdogg@example.com',
    password: 'examplePassword123!@#',
    domicile: 'Long Beach, California',
    gender: 'male',
    dateOfBirth: '1971-10-20',
  },
  {
    firstName: 'Ice',
    lastName: 'Cube',
    email: 'icecube@example.com',
    password: 'examplePassword123!@#',
    domicile: 'Crenshaw, California',
    gender: 'male',
    dateOfBirth: '1969-06-15',
  },
  {
    firstName: 'Tupac',
    lastName: 'Shakur',
    email: '2pac@example.com',
    password: 'examplePassword123!@#',
    domicile: 'New York',
    gender: 'male',
    dateOfBirth: '1971-06-16',
  },
  {
    firstName: 'Nate',
    lastName: 'Dogg',
    email: 'natedogg@example.com',
    password: 'examplePassword123!@#',
    domicile: 'Long Beach, California',
    gender: 'male',
    dateOfBirth: '1969-08-19',
  },
];
