export const mockedUsers = [
  {
    firstName: 'john',
    lastName: 'doe',
    email: 'johndoe@example.com',
    password: 'examplePassword123!@#',
    domicile: 'new york',
    gender: 'male',
    dateOfBirth: '1999-12-21',
  },
  {
    firstName: 'jane',
    lastName: 'doe',
    email: 'janedoe@example.com',
    password: 'examplePassword123!@#',
    domicile: 'london',
    gender: 'female',
    dateOfBirth: '2000-01-31',
  },
  {
    firstName: 'max',
    lastName: 'mustermann',
    email: 'maxmustermann@example.com',
    password: 'examplePassword123!@#',
    domicile: 'berlin',
    gender: 'male',
    dateOfBirth: '1989-07-12',
  },
  {
    firstName: 'jan',
    lastName: 'kowalski',
    email: 'jankowalski@example.com',
    password: 'examplePassword123!@#',
    domicile: 'warsaw',
    gender: 'male',
    dateOfBirth: '1997-10-09',
  },
  {
    firstName: 'anna',
    lastName: 'kowalska',
    email: 'annakowalska@example.com',
    password: 'examplePassword123!@#',
    domicile: 'cracow',
    gender: 'female',
    dateOfBirth: '1975-09-27',
  },
  {
    firstName: 'iwan',
    lastName: 'pietrowicz',
    email: 'iwanpietrowicz@example.com',
    password: 'examplePassword123!@#',
    domicile: 'moscow',
    gender: 'male',
    dateOfBirth: '1986-02-28',
  },
  {
    firstName: 'david',
    lastName: 'guetta',
    email: 'davidguetta@example.com',
    password: 'examplePassword123!@#',
    domicile: 'paris',
    gender: 'male',
    dateOfBirth: '1967-11-07',
  },
  {
    firstName: 'pop',
    lastName: 'smoke',
    email: 'popsmoke@example.com',
    password: 'examplePassword123!@#',
    domicile: 'new york',
    gender: 'male',
    dateOfBirth: '1999-07-20',
  },
  {
    firstName: 'fifty',
    lastName: 'cent',
    email: '50cent@example.com',
    password: 'examplePassword123!@#',
    domicile: 'new york',
    gender: 'male',
    dateOfBirth: '1975-07-06',
  },
  {
    firstName: 'snoop',
    lastName: 'dogg',
    email: 'snoopdogg@example.com',
    password: 'examplePassword123!@#',
    domicile: 'long beach, california',
    gender: 'male',
    dateOfBirth: '1971-10-20',
  },
  {
    firstName: 'ice',
    lastName: 'cube',
    email: 'icecube@example.com',
    password: 'examplePassword123!@#',
    domicile: 'crenshaw, california',
    gender: 'male',
    dateOfBirth: '1969-06-15',
  },
  {
    firstName: 'tupac',
    lastName: 'shakur',
    email: '2pac@example.com',
    password: 'examplePassword123!@#',
    domicile: 'new york',
    gender: 'male',
    dateOfBirth: '1971-06-16',
  },
  {
    firstName: 'nate',
    lastName: 'dogg',
    email: 'natedogg@example.com',
    password: 'examplePassword123!@#',
    domicile: 'long beach, california',
    gender: 'male',
    dateOfBirth: '1969-08-19',
  },
];
